from selenium import webdriver
from utils.log import logging
from utils.seleniumtools import find_element
import time

driver=driver = webdriver.Chrome(executable_path='chromedriver.exe')
driver.maximize_window()
driver.get("http://www.geron-e.com:8081/course/index.html")
# driver.add_cookie({"name":"sessionId","value":"003cc74922ea49db854e84368a3e5fde"})
# driver.refresh()
# enter_plan=find_element("xpath",'/html/body/div[3]/div/div/div/div[19]/div/div[3]/a')
# enter_question=find_element("xpath",'/html/body/div[3]/div[2]/div[2]/div/div[3]/div[2]/a')
# enter_plans=find_element("id","continueExercise")
# question1=find_element("xpath",'/html/body/div[5]/div/div[1]/div[3]/div')
# submit_answers1=find_element("id","nextTestQuestions")
# next_question=find_element("id","nextTestQuestions")

# find_element(driver,enter_plan).click()
# find_element(driver,enter_question).click()
# find_element(driver,enter_plans).click()
# find_element(driver,question1).click()
# find_element(driver,submit_answers1).click()
# find_element(driver,next_question).click()

try:
    time.sleep(3)
    #让页面滑动条到达最底端
    js="var q=document.documentElement.scrollTop=100000"  
    driver.execute_script(js)  
    time.sleep(2)  
    a=driver.find_element_by_xpath('//*[@id="course-list"]/div/div[19]/div/div[3]/a').click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="study"]/div[2]/div[1]/div/div[3]/div[2]/a').click()
    time.sleep(2)
    logging.info("开始刷题")
    driver.find_element_by_xpath('//*[@id="continueExercise"]/p').click()
    time.sleep(2)
    logging.info("单选题开始")
    driver.find_element_by_xpath('//*[@id="subject-1-12825"]/div[1]/div[3]/div/div/div').click()
    time.sleep(2)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12827"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12828"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12829"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    logging.info("单选题结束")
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("多选题开始")
    # driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[3]/div/div/span').click()
    # time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[4]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-2-12831"]/div[1]/div[2]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12831"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-2-12832"]/div[1]/div[3]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12832"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    logging.info("多选题结束")
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("判断题开始")
    driver.find_element_by_xpath('//*[@id="subject-1-12833"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12834"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12835"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12836"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("判断题结束")
    driver.find_element_by_xpath('//*[@id="wrongTopic"]').click()
    time.sleep(2)
    logging.info("刷错题开始")
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[3]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[4]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    logging.info("刷错题结束")
    driver.find_element_by_xpath('//*[@id="layui-layer5"]/div[3]/a[1]').click()
    time.sleep(1)
    res=driver.find_element_by_xpath('/html/body/div[4]/div[1]/div[1]/div/div[1]/span').text
    assert res =="刷题情况"

except Exception as e:
    logging.error('测试刷题失败:{}'.format(e))
    try:
        screenshot=time.strftime("%Y-%m-%d-%H_%M_%S", time.localtime(time.time()))
        driver.get_screenshot_as_file('C:\\pyweb\\errorscreenshot\\'+ screenshot +'.png')
        logging.info("截图保存成功")
    except Exception as a:
        logging.error('截图保存失败:{}'.format(a))
else:
    logging.info('测试刷题成功!!!')   
    print("刷题测试通过！！！") 
time.sleep(3)
driver.quit()
