from selenium import webdriver
from utils.seleniumtools import find_element
from utils.log import logging
import time

driver=driver = webdriver.Chrome(executable_path='chromedriver.exe')
driver.maximize_window()
driver.get("http://www.geron-e.com:8081/course/index.html")
driver.add_cookie({"name":"sessionId","value":"08a1ace966104355983e3a8305533702"})
driver.refresh()

try:
    time.sleep(3)
    # enter_plan=find_element("xpath",'/html/body/div[3]/div/div/div/div[19]/div/div[3]/a')
    # enter_question=find_element("xpath",'//*[@id="study"]/div[2]/div[1]/div/div[3]/div[2]/a')
    # enter_plans=find_element("id","exerciseDetails")
    # question1=find_element("xpath","/html/body/div[1]/div[5]/div/form/div/div[2]/div")
    # submit_answers1=find_element("id","exerciseDetails")
    # next_question=find_element("id","nextTestQuestions")

    # find_element(driver,enter_plan).click()
    # find_element(driver,enter_question).click()
    # find_element(driver,enter_plans).click()
    # find_element(driver,question1).click()
    # find_element(driver,submit_answers1).click()
    # find_element(driver,next_question).click()
    logging.info("进入学习课程")
    driver.find_element_by_xpath('//*[@id="course-list"]/div/div[1]/div/div[3]/a').click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="study"]/div[2]/div/div/div[3]/div[2]/a').click()
    time.sleep(2)
    logging.info("开始刷题")
    driver.find_element_by_xpath('//*[@id="continueExercise"]/p').click()
    time.sleep(2)
    logging.info("单选题开始")
    driver.find_element_by_xpath('//*[@id="subject-1-12825"]/div[1]/div[3]/div/div/div').click()
    time.sleep(2)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12827"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12828"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-3-12829"]/div[1]/div[3]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    logging.info("单选题结束")
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("多选题开始")
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[3]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[4]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12830"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-2-12831"]/div[1]/div[2]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12831"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-2-12832"]/div[1]/div[3]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="subject-2-12832"]/div[1]/div[5]/div/div/span').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    logging.info("多选题结束")
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("判断题开始")
    driver.find_element_by_xpath('//*[@id="subject-1-12833"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12834"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12835"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    driver.find_element_by_xpath('//*[@id="subject-1-12836"]/div[1]/div[2]/div/div/div').click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(1)
    driver.find_element_by_id("nextTestQuestions").click()
    time.sleep(2)
    logging.info("判断题结束")
    driver.find_element_by_xpath('//*[@id="brushQuestions"]').click()
    time.sleep(2)
    driver.find_element_by_xpath('/html/body/div[4]/span/a[3]').click()
    time.sleep(1)
    logging.info("返回刷题页面")
    res=driver.find_element_by_xpath('/html/body/div[4]/div[1]/div[1]/div/div[1]/span').text
    assert res =="刷题情况"
except Exception as e:
    logging.error('测试刷题失败:{}'.format(e))
else:
    logging.info('测试刷题成功!!!')   
    print("刷题测试通过！！！") 

driver.quit()



