from selenium import webdriver
from utils.log import logging
from utils.seleniumtools import find_element
import time
import unittest

class TestExam(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome(executable_path='chromedriver.exe')
        self.driver.maximize_window()
        self.driver.get("http://test.geron-e.com:8096/")
        self.driver.add_cookie({"name":"sessionId","value":"085666be8eb84acdaea48fbe1b0cd333"})
        self.driver.refresh()

    def tearDown(self):
        self.driver.quit()
        print("测试结束！")

    def test_01_exam(self):
        examination_center=("xpath",'/html/body/div[2]/div/ul/li[6]/a')
        enter_examination=("xpath",'//*[@id="beginExam1"]/td[2]/button')
        confirm_reminder=("xpath",'//*[@id="determine"]')
        confirmation_information=("xpath",'//*[@id="comeIn"]')
        subject1=("xpath",'//*[@id="stemId_18172"]/div[2]/label[1]/i')
        next_subject=("xpath",'//*[@id="next"]')
        subject2=("xpath",'//*[@id="stemId_18173"]/div[2]/label[1]/i')
        subject3=("xpath",'//*[@id="stemId_18174"]/div[2]/label[1]/i')
        subject4=("xpath",'//*[@id="stemId_18175"]/div[2]/label[1]/i')
        subject5_1=("xpath",'//*[@id="stemIdDiv_10500"]/div[2]/label[2]/i')
        subject5_2=("xpath",'//*[@id="stemIdDiv_10500"]/div[2]/label[3]/i')
        subject6_1=("xpath",'//*[@id="stemIdDiv_10501"]/div[2]/label[1]/i')
        subject6_2=("xpath",'//*[@id="stemIdDiv_10501"]/div[2]/label[4]/i')
        subject7_1=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[1]/i')
        subject7_2=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[2]/i')
        subject7_3=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[3]/i')
        subject7_4=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[4]/i')
        subject8=("xpath",'//*[@id="stemIdText_11013"]/div[2]/label[1]/i')
        subject9=("xpath",'//*[@id="stemIdText_11014"]/div[2]/label[2]/i')
        subject10=("xpath",'//*[@id="stemIdText_11015"]/div[2]/label[2]/i')
        submit=("xpath",'/html/body/div/div[3]/div/div[2]/div[3]/div[3]/span')
        confirm_submit=("xpath",'//*[@id="determine"]')

        try:
            find_element(self.driver,examination_center).click()
            find_element(self.driver,enter_examination).click()
            logging.info("进入考试系统")
            find_element(self.driver,confirm_reminder).click()
            find_element(self.driver,confirmation_information).click()
            logging.info("开始答题")
            find_element(self.driver,subject1).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject2).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject3).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject4).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject5_1).click()
            find_element(self.driver,subject5_2).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject6_1).click()
            find_element(self.driver,subject6_2).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject7_1).click()
            find_element(self.driver,subject7_2).click()
            find_element(self.driver,subject7_3).click()
            find_element(self.driver,subject7_4).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject8).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject9).click()
            find_element(self.driver,next_subject).click()
            find_element(self.driver,subject10).click()
            find_element(self.driver,next_subject).click()
            logging.info("答题结束")
            find_element(self.driver,submit).click()
            logging.info("提交试卷")
            find_element(self.driver,confirm_submit).click()
        except Exception as e:
            logging.error('正式考试失败:{}'.format(e))
            screenshot=time.strftime("%Y-%m-%d-%H_%M_%S", time.localtime(time.time()))
            self.driver.get_screenshot_as_file('C:\\pyweb\\errorscreenshot\\'+ screenshot +'.png')
            logging.info("截图保存成功")
        assert self.driver.title =="正式考试卷面"

# examination_center=("xpath",'/html/body/div[2]/div/ul/li[6]/a')
# enter_examination=("xpath",'//*[@id="beginExam1"]/td[2]/button')
# confirm_reminder=("xpath",'//*[@id="determine"]')
# confirmation_information=("xpath",'//*[@id="comeIn"]')
# subject1=("xpath",'//*[@id="stemId_18172"]/div[2]/label[1]/i')
# next_subject=("xpath",'//*[@id="next"]')
# subject2=("xpath",'//*[@id="stemId_18173"]/div[2]/label[1]/i')
# subject3=("xpath",'//*[@id="stemId_18174"]/div[2]/label[1]/i')
# subject4=("xpath",'//*[@id="stemId_18175"]/div[2]/label[1]/i')
# subject5_1=("xpath",'//*[@id="stemIdDiv_10500"]/div[2]/label[2]/i')
# subject5_2=("xpath",'//*[@id="stemIdDiv_10500"]/div[2]/label[3]/i')
# subject6_1=("xpath",'//*[@id="stemIdDiv_10501"]/div[2]/label[1]/i')
# subject6_2=("xpath",'//*[@id="stemIdDiv_10501"]/div[2]/label[4]/i')
# subject7_1=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[1]/i')
# subject7_2=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[2]/i')
# subject7_3=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[3]/i')
# subject7_4=("xpath",'//*[@id="stemIdDiv_10502"]/div[2]/label[4]/i')
# subject8=("xpath",'//*[@id="stemIdText_11013"]/div[2]/label[1]/i')
# subject9=("xpath",'//*[@id="stemIdText_11014"]/div[2]/label[2]/i')
# subject10=("xpath",'//*[@id="stemIdText_11015"]/div[2]/label[2]/i')
# submit=("xpath",'/html/body/div/div[3]/div/div[2]/div[3]/div[3]/span')
# confirm_submit=("xpath",'//*[@id="determine"]')


# find_element(driver,examination_center).click()
# find_element(driver,enter_examination).click()
# find_element(driver,confirm_reminder).click()
# find_element(driver,confirmation_information).click()
# find_element(driver,subject1).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject2).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject3).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject4).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject5_1).click()
# find_element(driver,subject5_2).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject6_1).click()
# find_element(driver,subject6_2).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject7_1).click()
# find_element(driver,subject7_2).click()
# find_element(driver,subject7_3).click()
# find_element(driver,subject7_4).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject8).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject9).click()
# find_element(driver,next_subject).click()
# find_element(driver,subject10).click()
# find_element(driver,next_subject).click()
# find_element(driver,submit).click()
# find_element(driver,confirm_submit).click()

# assert driver.title =="正式考试卷面"
# print("测试通过！！！")



